name = "gen_prism"
version = "0.1.0"
description = "gen_prism — BEAM process behaviour for prism operations. Five callbacks, one process."

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
